---
title: "DJSIR Jobs Summary"
author: "DJSIR EPPC Data + Analytics"
date: "`r Sys.Date()`"
pdf-engine: lualatex
execute:
  echo: false
format:
  pdf: 
    keep-tex: true
    documentclass: report
    include-in-header: "assets/preamble.tex"
    papersize: a4
    toc: false
    latex-auto-install: false
    block-headings: false
    geometry:
    - top=20mm
    - bottom=24mm
    - left=24mm
    - right=24mm
    - heightrounded
---


<!-- SETUP -->

```{r}
#| echo: false
#| output: false

# Packages
library(data.table)
library(lubridate)
library(fst)

# Latest data
indx <- fread("table_index.csv")
release_date <- indx[, as.Date(max(last_updated, na.rm = T))]
reference_date <- read_fst("data/jobs_data.fst", columns = "date")[[1]]
reference_date <- max(reference_date)
reference_month <- month.name[month(reference_date)]

# Determine release type
release_type <- Sys.getenv("update_type", "auto")


# Geneerate subtitle, chapter badges and TOC updated flags
if(!(release_type %in% c("headline", "regional", "industry"))){
  
  subtitle <- "ABS data update"
  badge <- c()
  toc_updated <-c()
  
} else {
  
  subtitle <- paste(
    reference_month, 
    switch(
      release_type,
      "headline" = "headline statistics",
      "regional" = "regional statistics",
      "industry" = "region and industry statistics"
    )
  )
  
  badge_col <- paste0("update_", release_type)
  badge_df <- indx[
    , 
    .(
      badge = if(sum(.SD[[1]]) / length(.SD[[1]]) >= 0.5){
        "\\hfill \\badge{\\normalfont{New}}"
      } else {
        ""
      },
     toc = if(sum(.SD[[1]]) / length(.SD[[1]]) >= 0.5){
        "\\hspace{3pt}\\small{\\badge{New}}"
      } else {
      ""
      }
    ),
    table_name,
    .SDcols = badge_col
  ]
  badge <- badge_df$badge
  names(badge) <- badge_df$table_name
  
  toc_updated <- badge_df$toc
  names(toc_updated) <- badge_df$table_name
}


```




<!-- TITLE PAGE -->

```{=tex}
\begin{titlepage}
\AddToShipoutPicture*{\BackgroundPic}
  \begin{flushright}
    \begin{varwidth}{4in}
      \begin{flushright}
        \color{black}
        \vspace*{10.65cm}
        {\Huge\bfseries Jobs Briefing}
        \linebreak
        \linebreak
        {\large `r subtitle`}
        \linebreak
        \linebreak
        `r format(release_date, "%e %B %Y")`
        \vfill
      \end{flushright}
    \end{varwidth}
  \end{flushright}
\end{titlepage}
```



<!-- TOC & Disclaimer page -->

```{=tex}
\pagenumbering{gobble}
\setcounter{tocdepth}{1}
\tableofcontents
\vspace*{\fill}
```
\copyright \enspace Department of Jobs, Skills, Industry and Regions, `r format(Sys.Date(), "%Y")` \newline \newline The content of this Victorian Government report is provided for information purposes only. No claim is made as to the accuracy or currency of any of the content in this report at any time. The Victorian Government and this agency (the Department of Jobs, Skills, Industry and Regions) do not accept any liability to any person for the information (or the use of such information) which is provided on this report, including information sourced or derived from third parties or incorporated into the report by reference. \newpage \pagenumbering{arabic}



\chapter[Talking points `r toc_updated["Overview"]`]{Talking points `r badge["Overview"]`} 
\input{./assets/talking_points/talking_points.tex}




\smallspacechapter[Employment Summary `r toc_updated["Overview"]`]{Employment Summary `r badge["Overview"]`}
\vfill
\input{./assets/latex_table/Overview.tex}
\vfill
\newpage




\vspace*{1mm}
\vfill
\section{Sex} 
\input{./assets/latex_table/Sex.tex}
\vfill




\section{Unemployment rate by state}
\input{./assets/latex_table/StateUnemployment.tex}
\vfill




\chapter[Youth `r toc_updated["Age"]`]{Youth `r badge["Age"]`}
DJSIR smooths youth statistics using 12-month average to remove volatility present in the data. While smoothing assists in observing underlying trends, it makes large month-to-month changes less apparent. Please note that regional and gender-based youth statistics update later in each month than other youth statistics. 


\input{./assets/latex_table/Age.tex}
\pagebreak




\vspace*{1mm}
\vfill
\section[Youth by region `r if(release_type %in% c("regional", "industry")) "\\emph{(updated)}"`]{Youth by region}
\input{./assets/latex_table/AgeRegion.tex}
\vfill




\chapter[Metropolitan Melbourne `r toc_updated["RegionMetroUnemployment"]`]{Metropolitan Melbourne `r badge["RegionMetroUnemployment"]`}
\vfill
\section{Metropolitan unemployment rate by state}
\input{./assets/latex_table/MetroUnemployment.tex}
\vfill
\pagebreak




\vspace*{1mm}
\vfill

## Employment across Greater Melbourne

\input{./assets/latex_table/RegionMetroEmployed.tex}
\vfill
\pagebreak

\ 
\vfill

## Unemployed persons across Greater Melbourne

\input{./assets/latex_table/RegionMetroUnemployed.tex}
\vfill
\pagebreak

\ 
\vfill

## Unemployment rate across Greater Melbourne

\input{./assets/latex_table/RegionMetroUnemployment.tex}
\vfill
\pagebreak

\ 
\vfill

## Participation rate across Greater Melbourne

\input{./assets/latex_table/RegionMetroParticipation.tex}
\vfill

\chapter[Regional Victoria `r toc_updated["RegionNonMetroUnemployment"]`]{Regional Victoria `r badge["RegionNonMetroUnemployment"]`}

\vfill

## Regional unemployment rate by state

\input{./assets/latex_table/NonMetroUnemployment.tex}
\vfill
\pagebreak

\ 
\vfill

## Employment across regional Victoria

\input{./assets/latex_table/RegionNonMetroEmployed.tex}
\vfill
\pagebreak

\ 
\vfill

## Unemployed persons across regional Victoria

\input{./assets/latex_table/RegionNonMetroUnemployed.tex}
\vfill
\pagebreak

\ 
\vfill

## Unemployment rate across regional Victoria

\input{./assets/latex_table/RegionNonMetroUnemployment.tex}
\vfill
\pagebreak

\ 
\vfill

## Participation rate across regional Victoria

\input{./assets/latex_table/RegionNonMetroParticipation.tex}
 
\vfill


\smallspacechapter[Industry `r toc_updated["Industry"]`]{Industry `r badge["Industry"]`}
\input{./assets/latex_table/Industry.tex}
